### PR TITLE
Newapi

### PR DESCRIPTION
**Pull request by kitech**
start upgrade to toxcore newapi.

full tested module: friend message api, file transfer api, group mesage api, examples, uint tests,

need improve or more test: toxav api

add i do some doc work about api upgrade:  http://nullget.sourceforge.net/?q=node/836

### CODE REVIEW

**Comment by aitjcize** [comment]
Thanks for your contribution! Can you fix the test as well?

**Comment by gbin** [comment]
ping on this one ? this has been breaking errbot for quite a while.

**Comment by kitech** [comment]
en, newapi is big change.

**Comment by Adman** [comment]
@kitech Is the echo.py example working?

**Comment by kitech** [comment]
the echo.py should not working. not yet update.

**Comment by mrshu** [comment]
@kitech https://github.com/kitech/PyTox/pull/1 should make both the `echo.py` and `phone.py` work again.

**Comment by kitech** [comment]
Any suggestion about version no?

**Pull request merged**
