### PR TITLE
Support stateless callbacks and update to TokTok/toxcore.

### PR DESCRIPTION
**Pull request by iphydf**
Also some minor fixes and adding support for the log callback.

### CODE REVIEW

**Comment by kitech** [comment]
maybe can create a toktok branch for the forked version.

**Comment by GrayHatter** [comment]
irungentoo's branch is stale. You should switch to toktok, and encourage your users to do the same.

**Comment by iphydf** [comment]
If you create a toktok branch, I'll make a pull request into that.

**Comment by kitech** [comment]
I pushed a toktok branch with pull/60 merged just now.

Now that can be used for later pull request from toktok.

 > If you create a toktok branch, I'll make a pull request into that.

**Pull request closed without merging**
