### PR TITLE
examples: EchoBot sends sent files back

### PR DESCRIPTION
**Pull request by mrshu**
* In the spirit of echoing everything back, EchoBot sends files the user
  sends back.

* In order to set a good example, the README got a few 'pythonic' fixes.

* In order for the tests to pass it was necessary to run `apt-get update`
  prior to other `apt-get` calls.

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

**Comment by mrshu** [comment]
@aitjcize would you mind checking this PR? It cleans the code a bit and adds a functionality that should have been there for a long time I believe.

**Comment by mrshu** [comment]
Sorry @aitjcize, I understand you do not have much time for this repository, my last message should have been addressed to @kitech.

**Comment by kitech** [comment]
nice about EchoBot and `pythonic`.
in the Travis build log, found nothing about what updated for `apt-get update`

**Comment by mrshu** [comment]
@kitech If you look for instance here: https://travis-ci.org/aitjcize/PyTox/jobs/99936648#L110 you can see that quite a few package lists have been updated. I suspect that some of these lists must have `yasm` in them since it fixed the problem.

**Comment by kitech** [comment]
Ok, since it's version related, just merged.

**Comment by mrshu** [comment]
Thanks a ton @kitech!

**Pull request merged**
