### PR TITLE
Newavapi

### PR DESCRIPTION
**Pull request by kitech**
Prepare for newav api upgrade.

Audio and video all done. Ready for merge.

### CODE REVIEW

**Comment by kitech** [comment]
Now video seem work fine.
But for audio, I hear nothing when run echo.py, even no noise audio.

**Comment by quininer** [comment]
:+1:

**Comment by kitech** [comment]
Aha, nice.

**Comment by kitech** [comment]
Oh, just now MIC for qTox setting no correct, has echo sound now.

**Pull request merged**
